# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:58
from __future__ import unicode_literals

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('num_of_module', models.PositiveIntegerField(default=0)),
                ('opened', models.BooleanField(default=False)),
                ('description', models.TextField(default='This course has no description.', validators=[course.models.validate_not_blank])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Instructor')),
            ],
        ),
    ]
