# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='num_of_module',
        ),
        migrations.AddField(
            model_name='course',
            name='number_of_module',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
