# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20161101_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number_of_module',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
