# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('number_of_course', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Component_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sequence', models.PositiveIntegerField()),
                ('file_field', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sequence', models.PositiveIntegerField()),
                ('image_field', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component_Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sequence', models.PositiveIntegerField()),
                ('text_field', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_module', models.PositiveIntegerField(default=0)),
                ('opened', models.BooleanField(default=False)),
                ('description', models.TextField(default='This course has no description.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_component', models.PositiveIntegerField(default=0)),
                ('sequence', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('identity_instructor', models.BooleanField(default=False)),
                ('identity_admin', models.BooleanField(default=False)),
                ('identity_hr', models.BooleanField(default=False)),
                ('current_enrollment', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='component_text',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdp.Module'),
        ),
        migrations.AddField(
            model_name='component_image',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdp.Module'),
        ),
        migrations.AddField(
            model_name='component_file',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdp.Module'),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('sdp.user',),
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('sdp.user',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('sdp.user',),
        ),
        migrations.CreateModel(
            name='Particiapnt',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('sdp.user',),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdp.Instructor'),
        ),
    ]
