# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(null=True)),
                ('module_progress', models.IntegerField(default=0)),
                ('component_progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Particiapnt',
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('sdp.user',),
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='component_file',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='component_image',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='component_text',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdp.Course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdp.Participant'),
        ),
    ]
