# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0002_auto_20161122_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='component_file',
            name='component_type',
            field=models.CharField(choices=[('T', 'Text'), ('F', 'File'), ('I', 'Image')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='component_image',
            name='component_type',
            field=models.CharField(choices=[('T', 'Text'), ('F', 'File'), ('I', 'Image')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='component_text',
            name='component_type',
            field=models.CharField(choices=[('T', 'Text'), ('F', 'File'), ('I', 'Image')], default='T', max_length=1),
        ),
    ]
