# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0005_auto_20161202_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component_video',
            old_name='file_field',
            new_name='url_field',
        ),
        migrations.AlterField(
            model_name='component_file',
            name='component_type',
            field=models.CharField(choices=[('T', 'Text'), ('F', 'File'), ('I', 'Image'), ('V', 'Video')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='component_image',
            name='component_type',
            field=models.CharField(choices=[('T', 'Text'), ('F', 'File'), ('I', 'Image'), ('V', 'Video')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='component_text',
            name='component_type',
            field=models.CharField(choices=[('T', 'Text'), ('F', 'File'), ('I', 'Image'), ('V', 'Video')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='component_video',
            name='component_type',
            field=models.CharField(choices=[('T', 'Text'), ('F', 'File'), ('I', 'Image'), ('V', 'Video')], default='T', max_length=1),
        ),
    ]
