# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0006_auto_20161202_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='component_progress',
        ),
    ]
