# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0007_remove_enrollment_component_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='component_progress',
            field=models.IntegerField(default=0),
        ),
    ]
