# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='number_of_component',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='module',
            name='sequence',
            field=models.PositiveIntegerField(),
        ),
    ]
