# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20161101_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='number_of_course',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
