# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sequence', models.PositiveIntegerField(blank=True)),
                ('file_field', models.FileField(upload_to='')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sequence', models.PositiveIntegerField(blank=True)),
                ('image_field', models.ImageField(upload_to='')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component_Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sequence', models.PositiveIntegerField(blank=True)),
                ('text_field', models.TextField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
