# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_file',
            name='sequence',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='component_image',
            name='sequence',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='component_text',
            name='sequence',
            field=models.PositiveIntegerField(),
        ),
    ]
