# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('identity_instructor', models.BooleanField(default=False)),
                ('identity_admin', models.BooleanField(default=False)),
                ('identity_hr', models.BooleanField(default=False)),
                ('current_enrollment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Particiapnt',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('user.user',),
        ),
    ]
